### ISSUE TITLE
wrong statement on Dockerfile.prod

### ISSUE THREAD

**Issue by henrfarias** [codeedu/imersao-fc6#1]
CMD ["npm", "start"].

**Comment by argentinaluiz** [comment]
Oi @henrfarias , tudo bem?

O Nest.js permite rodar seu servidor Node de ambos formas:

`npm start`

ou

`npm run start:prod`

Entendeu a ideia?

**Comment by henrfarias** [comment]
Boa tarde, @argentinaluiz ! 

Entendi sim. Não sabia dessa esperteza do nestjs, muito legal.
Porém, o problema que encontrei é no Dockerfile.prod do nextjs. Fiz o pull request, inclusive, após ajudar um colega que estava tendo problemas para subir a imagem no cluster por causa deste detalhe.

(*edit) Obrigado pela atenção, sou fã de vocês!

**Comment by argentinaluiz** [comment]
Hum @henrfarias , até verifique aqui o Dockerfile.prod do Next.js e está usando somente o `npm start`.

**Comment by henrfarias** [comment]
@argentinaluiz se você tiver interesse em acompanhar a discussão, este é o link da mensagem (https://discord.com/channels/917202955952881735/917210405963718716/943162403447783516)
